version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: todo
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  mysql_test:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todo_app_test
      MYSQL_USER: todo_test_user
      MYSQL_PASSWORD: todo_test_password
    ports:
      - "3307:3306"
    networks:
      - app-network
  
  backend:
    build: ./todo-backend
    ports:
      - "3001:3001"
    depends_on:
      - db
      - mysql_test
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/todo
      - TEST_DATABASE_URL=mysql://todo_test_user:todo_test_password@mysql_test:3306/todo_app_test
    volumes:
      - ./todo-backend:/app
      - /app/node_modules

  frontend:
    build: ./todo-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./todo-frontend:/app
      - /app/node_modules

  backend-tests:
    build: ./todo-backend
    command: npm run test:coverage
    depends_on:
      - mysql_test
    environment:
      - NODE_ENV=test
      - TEST_DATABASE_URL=mysql://todo_test_user:todo_test_password@mysql_test:3306/todo_app_test
    networks:
      - app-network

  frontend-tests:
    build: ./todo-frontend
    command: npm run test:coverage
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: